'use client';

import React, { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { 
  BrainCircuit, 
  Sparkles, 
  Code2, 
  BookOpen, 
  Calendar, 
  MessageSquare, 
  Send, 
  CheckCircle2, 
  AlertCircle, 
  Loader2, 
  HelpCircle,
  Lightbulb,
  Building2,
  ChevronDown,
  ChevronUp
} from 'lucide-react';
import { interviewApi, jobsApi } from '../../services/api';
import { useAuth } from '../../context/AuthContext';

function InterviewPrepContent() {
  const searchParams = useSearchParams();
  const queryJobId = searchParams.get('jobId');

  const { user, resume, isAuthenticated, showToast, demoLogin } = useAuth();

  const [jobId, setJobId] = useState(queryJobId || '');
  const [targetRole, setTargetRole] = useState('Full Stack Developer (Fresher)');
  const [selectedJob, setSelectedJob] = useState(null);
  const [loading, setLoading] = useState(false);
  const [prepKit, setPrepKit] = useState(null);
  const [activeTab, setActiveTab] = useState('questions');
  const [expandedQuestion, setExpandedQuestion] = useState(null);

  // Mock Answer Practice State
  const [activePracticeQuestion, setActivePracticeQuestion] = useState(null);
  const [userAnswer, setUserAnswer] = useState('');
  const [evaluatingAnswer, setEvaluatingAnswer] = useState(false);
  const [mockEvaluation, setMockEvaluation] = useState(null);

  useEffect(() => {
    if (queryJobId) {
      loadJob(queryJobId);
    } else {
      handleGenerateKit();
    }
  }, [queryJobId]);

  const loadJob = async (id) => {
    try {
      const res = await jobsApi.getJobById(id);
      if (res.success && res.job) {
        setSelectedJob(res.job);
        setTargetRole(res.job.title);
        handleGenerateKit(id, res.job.title);
      }
    } catch (err) {
      console.warn('Load job err:', err);
    }
  };

  const handleGenerateKit = async (specificJobId, roleName) => {
    setLoading(true);
    setMockEvaluation(null);
    try {
      const res = await interviewApi.generateInterviewKit(
        specificJobId || jobId || undefined,
        roleName || targetRole,
        selectedJob?.description || undefined
      );

      if (res.success && res.prepKit) {
        setPrepKit(res.prepKit);
        showToast('AI Interview Preparation Kit generated by Gemini!', 'success');
      }
    } catch (err) {
      showToast(err.message || 'Failed to generate prep kit', 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleEvaluateAnswer = async (question) => {
    if (!userAnswer.trim()) {
      showToast('Please type your mock response first.', 'error');
      return;
    }

    setEvaluatingAnswer(true);
    try {
      const res = await interviewApi.submitMockAnswer(
        question,
        userAnswer,
        targetRole
      );
      if (res.success && res.evaluation) {
        setMockEvaluation(res.evaluation);
        showToast('Gemini AI evaluated your answer!', 'success');
      }
    } catch (err) {
      showToast(err.message || 'Failed to evaluate answer', 'error');
    } finally {
      setEvaluatingAnswer(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8">
      
      {/* Header */}
      <div>
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-indigo-950/60 border border-indigo-800/60 text-indigo-300 text-xs font-semibold mb-2">
          <BrainCircuit className="w-3.5 h-3.5 text-indigo-400" />
          <span>Feature 3: AI Interview Preparation</span>
        </div>
        <h1 className="text-3xl font-extrabold text-white tracking-tight">Gemini Role-Specific Interview Kit</h1>
        <p className="text-zinc-400 text-sm mt-1">
          Generate technical questions, coding problems, and personalized 7-day preparation roadmaps based on your resume and target job.
        </p>
      </div>

      {/* Target Role & Generator Configuration */}
      <div className="p-6 rounded-3xl bg-zinc-900/60 border border-zinc-800/80 shadow-xl backdrop-blur-md">
        <div className="flex flex-col md:flex-row items-center justify-between gap-4">
          
          <div className="flex-1 w-full space-y-1">
            <label className="text-xs font-semibold text-zinc-300">Target Role / Position</label>
            <input
              type="text"
              value={targetRole}
              onChange={(e) => setTargetRole(e.target.value)}
              placeholder="e.g. Associate Software Engineer, Frontend Developer (React), Full Stack Fresher"
              className="w-full px-4 py-2.5 rounded-xl bg-zinc-950 border border-zinc-800 text-white text-xs placeholder:text-zinc-600 focus:outline-none focus:border-cyan-500"
            />
          </div>

          {selectedJob && (
            <div className="w-full md:w-auto p-3 rounded-xl bg-zinc-950 border border-zinc-800 text-xs text-zinc-300">
              <span className="text-[10px] text-zinc-500 font-bold block uppercase">Customized for Job</span>
              <span className="font-semibold text-white">{selectedJob.title}</span> at <span className="text-cyan-400">{selectedJob.company}</span>
            </div>
          )}

          <div className="w-full md:w-auto pt-4 md:pt-0">
            <button
              onClick={() => handleGenerateKit(jobId, targetRole)}
              disabled={loading}
              className="w-full md:w-auto px-6 py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-indigo-600 hover:from-cyan-400 hover:to-indigo-500 text-white text-xs font-bold shadow-lg shadow-indigo-600/20 flex items-center justify-center gap-2 whitespace-nowrap transition-all"
            >
              {loading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Generating Prep Kit...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-cyan-300" />
                  Generate Custom AI Prep Kit
                </>
              )}
            </button>
          </div>

        </div>
      </div>

      {/* Main Content Area */}
      {loading ? (
        <div className="py-24 flex flex-col items-center justify-center space-y-3">
          <Loader2 className="w-8 h-8 text-cyan-400 animate-spin" />
          <p className="text-xs text-zinc-400 font-medium">Gemini AI is crafting your role-specific interview kit...</p>
        </div>
      ) : prepKit ? (
        <div className="space-y-6">
          
          {/* Navigation Tabs */}
          <div className="flex items-center gap-2 overflow-x-auto pb-2 border-b border-zinc-800 scrollbar-none">
            {[
              { id: 'questions', label: 'Technical Questions', icon: HelpCircle, count: prepKit.roleQuestions?.length },
              { id: 'coding', label: 'Coding Challenges', icon: Code2, count: prepKit.codingProblems?.length },
              { id: 'topics', label: 'Core Technical Topics', icon: BookOpen, count: prepKit.technicalTopics?.length },
              { id: 'behavioral', label: 'Behavioral & STAR', icon: MessageSquare, count: prepKit.behavioralQuestions?.length },
              { id: 'roadmap', label: '7-Day Preparation Plan', icon: Calendar, count: prepKit.personalizedRoadmap?.length },
            ].map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                    activeTab === tab.id
                      ? 'bg-zinc-800 text-white border border-zinc-700 shadow-sm'
                      : 'text-zinc-400 hover:text-white bg-zinc-950/40 hover:bg-zinc-900 border border-transparent'
                  }`}
                >
                  <Icon className="w-3.5 h-3.5 text-cyan-400" />
                  <span>{tab.label}</span>
                  {tab.count !== undefined && (
                    <span className="px-1.5 py-0.2 rounded-full text-[10px] bg-zinc-900 border border-zinc-700 text-zinc-300">
                      {tab.count}
                    </span>
                  )}
                </button>
              );
            })}
          </div>

          {/* TAB 1: Technical Questions & Interactive Mock Answer */}
          {activeTab === 'questions' && (
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
              
              {/* Question list */}
              <div className="lg:col-span-7 space-y-4">
                {(prepKit.roleQuestions || []).map((q, idx) => {
                  const isExpanded = expandedQuestion === idx;

                  return (
                    <div
                      key={idx}
                      className="p-5 rounded-2xl bg-zinc-900/60 border border-zinc-800/80 space-y-3 transition-all shadow-md"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div className="space-y-1">
                          <span className="text-[10px] font-bold text-cyan-400 uppercase tracking-wider">
                            {q.category || 'Core Engineering'}
                          </span>
                          <h3 className="text-sm font-bold text-white leading-snug">
                            Q{idx + 1}. {q.question}
                          </h3>
                        </div>
                      </div>

                      <div className="flex items-center gap-3 pt-1">
                        <button
                          onClick={() => setExpandedQuestion(isExpanded ? null : idx)}
                          className="text-xs font-semibold text-zinc-400 hover:text-white flex items-center gap-1 transition-colors"
                        >
                          <span>{isExpanded ? 'Hide Model Answer' : 'Show Model Answer'}</span>
                          {isExpanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
                        </button>

                        <button
                          onClick={() => {
                            setActivePracticeQuestion(idx);
                            setMockEvaluation(null);
                            setUserAnswer('');
                          }}
                          className="text-xs font-bold text-cyan-400 hover:text-cyan-300 flex items-center gap-1 transition-colors"
                        >
                          <Sparkles className="w-3 h-3" />
                          <span>Practice Mock Answer</span>
                        </button>
                      </div>

                      {/* Expandable Model Answer */}
                      {isExpanded && (
                        <div className="mt-3 p-4 rounded-xl bg-zinc-950 border border-zinc-800 space-y-2 text-xs text-zinc-300 leading-relaxed">
                          <p className="font-medium text-white">{q.modelAnswer}</p>
                          {q.keyTakeaway && (
                            <div className="p-2.5 rounded-lg bg-emerald-950/20 border border-emerald-500/20 text-[11px] text-emerald-300">
                              <span className="font-bold">What interviewers evaluate:</span> {q.keyTakeaway}
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>

              {/* Right: Interactive Mock Answer Practice Console */}
              <div className="lg:col-span-5">
                <div className="sticky top-24 p-6 rounded-3xl bg-zinc-900/80 border border-cyan-500/30 shadow-2xl space-y-4">
                  <div className="flex items-center justify-between pb-3 border-b border-zinc-800">
                    <div className="flex items-center gap-2">
                      <Sparkles className="w-4 h-4 text-cyan-400" />
                      <h4 className="text-xs font-bold text-white uppercase tracking-wider">
                        Interactive Mock Interview Evaluator
                      </h4>
                    </div>
                    <span className="text-[10px] text-emerald-400 font-semibold">Gemini AI</span>
                  </div>

                  {activePracticeQuestion !== null ? (
                    <div className="space-y-3">
                      <div className="p-3 rounded-xl bg-zinc-950 border border-zinc-800 text-xs text-zinc-200 font-medium">
                        Q: {prepKit.roleQuestions?.[activePracticeQuestion]?.question}
                      </div>

                      <div>
                        <label className="text-xs font-semibold text-zinc-400 block mb-1">
                          Your Answer:
                        </label>
                        <textarea
                          rows={6}
                          value={userAnswer}
                          onChange={(e) => setUserAnswer(e.target.value)}
                          placeholder="Type how you would explain this to an interviewer (e.g. key principles, trade-offs, real-world project example)..."
                          className="w-full p-3 rounded-xl bg-zinc-950 border border-zinc-800 text-xs text-white placeholder:text-zinc-600 focus:outline-none focus:border-cyan-500"
                        />
                      </div>

                      <button
                        onClick={() => handleEvaluateAnswer(prepKit.roleQuestions?.[activePracticeQuestion]?.question)}
                        disabled={evaluatingAnswer}
                        className="w-full py-2.5 rounded-xl bg-gradient-to-r from-cyan-500 to-indigo-600 hover:from-cyan-400 hover:to-indigo-500 text-white text-xs font-bold shadow-md shadow-indigo-600/20 flex items-center justify-center gap-2 transition-all"
                      >
                        {evaluatingAnswer ? (
                          <>
                            <Loader2 className="w-3.5 h-3.5 animate-spin" />
                            Evaluating with Gemini...
                          </>
                        ) : (
                          <>
                            <Send className="w-3.5 h-3.5" />
                            Submit Answer for AI Rating & Feedback
                          </>
                        )}
                      </button>

                      {/* Mock Evaluation Feedback Result */}
                      {mockEvaluation && (
                        <div className="mt-4 p-4 rounded-2xl bg-zinc-950 border border-zinc-800 space-y-3 text-xs">
                          <div className="flex items-center justify-between">
                            <span className="font-bold text-white">AI Feedback</span>
                            <div className="px-2.5 py-1 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 font-black text-sm">
                              {mockEvaluation.score}/10
                            </div>
                          </div>

                          <p className="text-zinc-300 leading-relaxed">
                            {mockEvaluation.feedback}
                          </p>

                          {mockEvaluation.strengths && (
                            <div className="space-y-1">
                              <span className="text-[11px] font-bold text-emerald-400">Strengths:</span>
                              {mockEvaluation.strengths.map((str, i) => (
                                <p key={i} className="text-zinc-400 text-[11px]">• {str}</p>
                              ))}
                            </div>
                          )}

                          {mockEvaluation.improvementPoints && (
                            <div className="space-y-1">
                              <span className="text-[11px] font-bold text-amber-400">How to get 10/10:</span>
                              {mockEvaluation.improvementPoints.map((imp, i) => (
                                <p key={i} className="text-zinc-400 text-[11px]">• {imp}</p>
                              ))}
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  ) : (
                    <div className="py-8 text-center text-xs text-zinc-500 space-y-2">
                      <MessageSquare className="w-8 h-8 text-zinc-700 mx-auto" />
                      <p>Click "Practice Mock Answer" on any question to test your verbal/technical explanation and get Gemini AI rating & feedback.</p>
                    </div>
                  )}

                </div>
              </div>

            </div>
          )}

          {/* TAB 2: Coding Challenges */}
          {activeTab === 'coding' && (
            <div className="space-y-4">
              {(prepKit.codingProblems || []).map((codeQ, idx) => (
                <div key={idx} className="p-6 rounded-3xl bg-zinc-900/60 border border-zinc-800/80 space-y-4">
                  <div className="flex items-center justify-between">
                    <h3 className="text-base font-bold text-white flex items-center gap-2">
                      <Code2 className="w-4 h-4 text-cyan-400" />
                      {codeQ.title}
                    </h3>
                    <span className={`px-2.5 py-0.5 rounded-full text-xs font-bold border ${
                      codeQ.difficulty === 'Easy'
                        ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                        : 'bg-amber-500/10 text-amber-400 border-amber-500/30'
                    }`}>
                      {codeQ.difficulty}
                    </span>
                  </div>

                  <p className="text-xs text-zinc-300 leading-relaxed font-mono">
                    {codeQ.problemStatement}
                  </p>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="p-3.5 rounded-xl bg-zinc-950 border border-zinc-800 text-xs space-y-1">
                      <span className="text-[10px] font-bold uppercase text-zinc-500 tracking-wider">Example & Constraints</span>
                      <p className="font-mono text-cyan-300">{codeQ.example}</p>
                      {codeQ.constraints && <p className="text-[11px] text-zinc-500">{codeQ.constraints}</p>}
                    </div>

                    <div className="p-3.5 rounded-xl bg-zinc-950 border border-zinc-800 text-xs space-y-1">
                      <span className="text-[10px] font-bold uppercase text-amber-400 tracking-wider">Interviewer Hint</span>
                      <p className="text-zinc-300">{codeQ.hint}</p>
                    </div>
                  </div>

                  <div className="p-3.5 rounded-xl bg-indigo-950/20 border border-indigo-500/20 text-xs space-y-1">
                    <span className="font-bold text-indigo-300 block">Recommended Optimal Approach</span>
                    <p className="text-zinc-300">{codeQ.recommendedApproach}</p>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* TAB 3: Core Technical Topics */}
          {activeTab === 'topics' && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {(prepKit.technicalTopics || []).map((topic, idx) => (
                <div key={idx} className="p-5 rounded-2xl bg-zinc-900/60 border border-zinc-800/80 space-y-2">
                  <div className="flex items-center justify-between">
                    <h4 className="text-sm font-bold text-white">{topic.topic}</h4>
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-cyan-950 text-cyan-300 border border-cyan-800">
                      {topic.importance}
                    </span>
                  </div>
                  <p className="text-xs text-zinc-400 leading-relaxed">{topic.summary}</p>
                </div>
              ))}
            </div>
          )}

          {/* TAB 4: Behavioral Questions */}
          {activeTab === 'behavioral' && (
            <div className="space-y-4">
              {(prepKit.behavioralQuestions || []).map((bq, idx) => (
                <div key={idx} className="p-5 rounded-2xl bg-zinc-900/60 border border-zinc-800/80 space-y-2.5">
                  <h4 className="text-sm font-bold text-white">Q{idx + 1}. {bq.question}</h4>
                  <div className="p-3.5 rounded-xl bg-zinc-950 border border-zinc-800 text-xs space-y-1">
                    <span className="font-bold text-cyan-400 flex items-center gap-1.5 text-[11px]">
                      <Lightbulb className="w-3.5 h-3.5" /> STAR Framework Tip
                    </span>
                    <p className="text-zinc-300 leading-relaxed">{bq.starTip}</p>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* TAB 5: 7-Day Personalized Roadmap */}
          {activeTab === 'roadmap' && (
            <div className="space-y-3">
              {(prepKit.personalizedRoadmap || []).map((step, idx) => (
                <div key={idx} className="p-5 rounded-2xl bg-zinc-900/60 border border-zinc-800/80 flex items-start gap-4">
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-tr from-cyan-500 to-indigo-600 flex flex-col items-center justify-center text-white shrink-0 font-bold shadow-md">
                    <span className="text-[10px] uppercase tracking-wider">Day</span>
                    <span className="text-sm">{idx + 1}</span>
                  </div>
                  <div className="space-y-1.5 flex-1">
                    <h4 className="text-sm font-bold text-white">{step.focus}</h4>
                    <div className="space-y-1 text-xs text-zinc-400">
                      {(step.actionItems || []).map((item, i) => (
                        <p key={i} className="flex items-start gap-2">
                          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0 mt-0.5" />
                          <span>{item}</span>
                        </p>
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}

        </div>
      ) : null}

    </div>
  );
}

export default function InterviewPrepPage() {
  return (
    <Suspense fallback={
      <div className="min-h-[70vh] flex flex-col items-center justify-center space-y-3">
        <Loader2 className="w-8 h-8 text-cyan-400 animate-spin" />
        <p className="text-xs text-zinc-400">Loading Interview Prep Engine...</p>
      </div>
    }>
      <InterviewPrepContent />
    </Suspense>
  );
}
